on:
  push:
  #   tags:
  #   - '*foobar*'

env:
  MY_ENV_VARIABLE: "oli netti"

jobs:
  asdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: asdf

        run: |
          echo $GITHUB_ENV
          sh script.sh

