on:
  push:
  #   tags:
  #   - '*foobar*'

jobs:
  asdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: asdf
        env:
          MY_ENV_VARIABLE: "oli netti"
        run: |
          echo $GITHUB_ENV
          sh script.sh

